name: Version
main: TheFixDev\Version\Main
api: 4.0.0
version: 1.0.0
author: TheFixDev
description: This plugin deleted the Commands /ver and /about
website: https://github.com/TheFixDev/Version
